"""Create wallets, transactions and blocks

Revision ID: de608e8c8965
Revises: 184cd895590b
Create Date: 2025-07-18 11:48:41.161143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de608e8c8965'
down_revision: Union[str, Sequence[str], None] = '184cd895590b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'wallets',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False, unique=True),
        sa.Column('public_key', sa.Text(), nullable=False),
        sa.Column('balance_fiat', sa.Float(), nullable=False, server_default='0'),
        sa.Column('balance_ouro', sa.Float(), nullable=False, server_default='0')
    )
    op.create_table(
        'blocks',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('index', sa.Integer(), nullable=False, unique=True),
        sa.Column('timestamp', sa.String(), nullable=False),
        sa.Column('previous_hash', sa.String(), nullable=False),
        sa.Column('nonce', sa.Integer(), nullable=False),
        sa.Column('hash', sa.String(), nullable=False)
    )
    op.create_table(
        'transactions',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('from_address', sa.Text(), nullable=False),
        sa.Column('to_address', sa.Text(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('nonce', sa.Integer(), nullable=False),
        sa.Column('fee', sa.Float(), nullable=False, server_default='0'),
        sa.Column('data', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=False),
        sa.Column('signature', sa.Text(), nullable=False),
        sa.Column('block_id', sa.Integer(), sa.ForeignKey('blocks.id'), nullable=True)
    )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
